### ISSUE TITLE
Propose for a logo for Utopmod

### ISSUE THREAD

**Issue by jbeguna04** [tolgahanuzun/Utopmod#6]
Hi, Good day! I would like to propose my logo designs for utopmod. Thank You!
I would like to ask if what colors do you prefer in your project?

## These are my proposed design in your project:
![cvvvvvvv](https://user-images.githubusercontent.com/35353768/37861886-4236ae32-2f7e-11e8-914d-1ab3aeb2543d.png)
#### Concept
![dsgtyergb](https://user-images.githubusercontent.com/35353768/37862096-69a4de68-2f82-11e8-8bed-25c461ceb17c.png)

Hope you like it. Please tell me your suggestion. Thank You!

**Comment by tolgahanuzun** [comment]
I do not like the colors. The colors came to me so discordantly.

**Comment by jbeguna04** [comment]
aknowledge sir. Do you have prefrerred colors for the logo?

**Comment by tolgahanuzun** [comment]
I will not say anything. Because I do not understand enough to give a suggestion. But I did not like the green color.

**Comment by jbeguna04** [comment]
Okay sir Ill just send various color design. Thank You

**Comment by jbeguna04** [comment]
There are some color combinations of the logo
![erygdfg](https://user-images.githubusercontent.com/35353768/37862389-e6f73362-2f86-11e8-88b0-265f5b98dab9.png)

**Comment by tolgahanuzun** [comment]
Number 3 is not bad. You can post it like that. I will last choose it at 27 for logo task :)

**Comment by jbeguna04** [comment]
Ill comment this to your post in utopian sir

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/37863758-8c673f06-2f9e-11e8-91ad-6d94d7b0407f.png)

Here is it. Hope you like it
