### ISSUE TITLE
logo for Utopmod telegram bot

### ISSUE THREAD

**Issue by familqasimov** [tolgahanuzun/Utopmod#8]
Hi sir tolgahanuzun, I look at your task reguest today. I made a logo for your wish. If you give permission to participate in this contribution, I am delighted.

![bot logo](https://user-images.githubusercontent.com/36432269/37869455-49ca9e30-2fd1-11e8-8746-6caedc9b842c.png)
![work2](https://user-images.githubusercontent.com/36432269/37869460-59c08714-2fd1-11e8-948c-30e88d7c57a0.png)
![work3](https://user-images.githubusercontent.com/36432269/37869461-6499cc4a-2fd1-11e8-95bb-a6d852b43a30.png)

**Comment by tolgahanuzun** [comment]
It is nice. Could you add a post link to my steemit post?

**Comment by familqasimov** [comment]
I'm sharing my post. I wish everybody good luck.
